"""Add profile information to user model

Revision ID: 5fb9eaf9bce2
Revises: dee31c02f462
Create Date: 2025-01-12 10:20:21.990163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb9eaf9bce2'
down_revision = 'dee31c02f462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=21), nullable=True))
        batch_op.add_column(sa.Column('first_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('second_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('zip_code')
        batch_op.drop_column('second_address')
        batch_op.drop_column('first_address')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
